[2024-11-30T15:55:31.525+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-30T15:55:31.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqlite_to_clickhouse.sqlite_to_clickhouse manual__2024-11-30T15:55:28.641579+00:00 [queued]>
[2024-11-30T15:55:31.608+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqlite_to_clickhouse.sqlite_to_clickhouse manual__2024-11-30T15:55:28.641579+00:00 [queued]>
[2024-11-30T15:55:31.608+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-30T15:55:31.612+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): sqlite_to_clickhouse> on 2024-11-30 15:55:28.641579+00:00
[2024-11-30T15:55:31.616+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-30T15:55:31.617+0000] {standard_task_runner.py:72} INFO - Started process 99 to run task
[2024-11-30T15:55:31.617+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sqlite_to_clickhouse', 'sqlite_to_clickhouse', 'manual__2024-11-30T15:55:28.641579+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp5m2emqrb']
[2024-11-30T15:55:31.618+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask sqlite_to_clickhouse
[2024-11-30T15:55:31.636+0000] {task_command.py:467} INFO - Running <TaskInstance: sqlite_to_clickhouse.sqlite_to_clickhouse manual__2024-11-30T15:55:28.641579+00:00 [running]> on host a043e4de3740
[2024-11-30T15:55:31.663+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqlite_to_clickhouse' AIRFLOW_CTX_TASK_ID='sqlite_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T15:55:28.641579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T15:55:28.641579+00:00'
[2024-11-30T15:55:31.664+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-30T15:55:31.664+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-30T15:55:31.664+0000] {logging_mixin.py:190} INFO - Current task name:sqlite_to_clickhouse state:running start_date:2024-11-30 15:55:31.606163+00:00
[2024-11-30T15:55:31.664+0000] {logging_mixin.py:190} INFO - Dag name:sqlite_to_clickhouse and current dag run status:running
[2024-11-30T15:55:31.664+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-30T15:55:31.670+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 11, in sqlite_to_clickhouse
    records = sqlite_hook.get_records('SELECT * FROM some_sqlite_table')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 356, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 485, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 609, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 40, in get_conn
    sqlalchemy_uri = self.get_uri()
                     ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 50, in get_uri
    airflow_conn = self.get_connection(conn_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `sqlite_default` isn't defined
[2024-11-30T15:55:31.673+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-30T15:55:31.673+0000] {logging_mixin.py:190} INFO - Task start:2024-11-30 15:55:31.606163+00:00 end:2024-11-30 15:55:31.673486+00:00 duration:0.067323
[2024-11-30T15:55:31.673+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): sqlite_to_clickhouse> dag:<DAG: sqlite_to_clickhouse> dagrun:<DagRun sqlite_to_clickhouse @ 2024-11-30 15:55:28.641579+00:00: manual__2024-11-30T15:55:28.641579+00:00, state:running, queued_at: 2024-11-30 15:55:28.688887+00:00. externally triggered: True>
[2024-11-30T15:55:31.673+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `sqlite_default` isn't defined
[2024-11-30T15:55:31.674+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sqlite_to_clickhouse, task_id=sqlite_to_clickhouse, run_id=manual__2024-11-30T15:55:28.641579+00:00, execution_date=20241130T155528, start_date=20241130T155531, end_date=20241130T155531
[2024-11-30T15:55:31.679+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-30T15:55:31.679+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task sqlite_to_clickhouse (The conn_id `sqlite_default` isn't defined; 99)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 11, in sqlite_to_clickhouse
    records = sqlite_hook.get_records('SELECT * FROM some_sqlite_table')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 356, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 485, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 609, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 40, in get_conn
    sqlalchemy_uri = self.get_uri()
                     ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 50, in get_uri
    airflow_conn = self.get_connection(conn_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `sqlite_default` isn't defined
[2024-11-30T15:55:31.718+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-30T15:55:31.725+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T15:55:31.726+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
