[2024-11-30T16:40:56.667+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-30T16:40:56.678+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_income_aggregate.update_income_aggregate manual__2024-11-30T16:40:55.339776+00:00 [queued]>
[2024-11-30T16:40:56.683+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_income_aggregate.update_income_aggregate manual__2024-11-30T16:40:55.339776+00:00 [queued]>
[2024-11-30T16:40:56.683+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-30T16:40:56.693+0000] {taskinstance.py:2889} INFO - Executing <Task(ClickHouseOperator): update_income_aggregate> on 2024-11-30 16:40:55.339776+00:00
[2024-11-30T16:40:56.697+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-30T16:40:56.698+0000] {standard_task_runner.py:72} INFO - Started process 142 to run task
[2024-11-30T16:40:56.698+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'update_income_aggregate', 'update_income_aggregate', 'manual__2024-11-30T16:40:55.339776+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp80n4aiiq']
[2024-11-30T16:40:56.699+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask update_income_aggregate
[2024-11-30T16:40:56.719+0000] {task_command.py:467} INFO - Running <TaskInstance: update_income_aggregate.update_income_aggregate manual__2024-11-30T16:40:55.339776+00:00 [running]> on host 66a40688d358
[2024-11-30T16:40:56.857+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_income_aggregate' AIRFLOW_CTX_TASK_ID='update_income_aggregate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T16:40:55.339776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T16:40:55.339776+00:00'
[2024-11-30T16:40:56.858+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-30T16:40:56.858+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-30T16:40:56.858+0000] {logging_mixin.py:190} INFO - Current task name:update_income_aggregate state:running start_date:2024-11-30 16:40:56.679538+00:00
[2024-11-30T16:40:56.858+0000] {logging_mixin.py:190} INFO - Dag name:update_income_aggregate and current dag run status:running
[2024-11-30T16:40:56.858+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-30T16:40:56.861+0000] {base.py:84} INFO - Retrieving connection 'clickhouse_test'
[2024-11-30T16:40:56.862+0000] {clickhouse.py:79} INFO - SELECT now()
[2024-11-30T16:40:56.868+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 528, in receive_hello
    raise self.receive_exception()
clickhouse_driver.errors.ServerException: Code: 516.
DB::Exception: clickhouse_admin: Authentication failed: password is incorrect, or there is no user with such name.. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, String const&) const @ 0x000000000ed2a3e0
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000000fe3cc28
4. DB::TCPHandler::receiveHello() @ 0x000000001100f318
5. DB::TCPHandler::runImpl() @ 0x0000000011006638
6. DB::TCPHandler::run() @ 0x000000001101d7e4
7. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
9. Poco::PooledThread::run() @ 0x000000001385d0b8
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
11. ? @ 0x000000000007d5c8
12. ? @ 0x00000000000e5edc

[2024-11-30T16:40:56.872+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-30T16:40:56.873+0000] {logging_mixin.py:190} INFO - Task start:2024-11-30 16:40:56.679538+00:00 end:2024-11-30 16:40:56.872753+00:00 duration:0.193215
[2024-11-30T16:40:56.873+0000] {logging_mixin.py:190} INFO - Task:<Task(ClickHouseOperator): update_income_aggregate> dag:<DAG: update_income_aggregate> dagrun:<DagRun update_income_aggregate @ 2024-11-30 16:40:55.339776+00:00: manual__2024-11-30T16:40:55.339776+00:00, state:running, queued_at: 2024-11-30 16:40:55.351191+00:00. externally triggered: True>
[2024-11-30T16:40:56.873+0000] {logging_mixin.py:190} INFO - Failure caused by Code: 516.
DB::Exception: clickhouse_admin: Authentication failed: password is incorrect, or there is no user with such name.. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, String const&) const @ 0x000000000ed2a3e0
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000000fe3cc28
4. DB::TCPHandler::receiveHello() @ 0x000000001100f318
5. DB::TCPHandler::runImpl() @ 0x0000000011006638
6. DB::TCPHandler::run() @ 0x000000001101d7e4
7. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
9. Poco::PooledThread::run() @ 0x000000001385d0b8
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
11. ? @ 0x000000000007d5c8
12. ? @ 0x00000000000e5edc
[2024-11-30T16:40:56.873+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=update_income_aggregate, task_id=update_income_aggregate, run_id=manual__2024-11-30T16:40:55.339776+00:00, execution_date=20241130T164055, start_date=20241130T164056, end_date=20241130T164056
[2024-11-30T16:40:56.878+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-30T16:40:56.878+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task update_income_aggregate (Code: 516.
DB::Exception: clickhouse_admin: Authentication failed: password is incorrect, or there is no user with such name.. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, String const&) const @ 0x000000000ed2a3e0
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000000fe3cc28
4. DB::TCPHandler::receiveHello() @ 0x000000001100f318
5. DB::TCPHandler::runImpl() @ 0x0000000011006638
6. DB::TCPHandler::run() @ 0x000000001101d7e4
7. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
9. Poco::PooledThread::run() @ 0x000000001385d0b8
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
11. ? @ 0x000000000007d5c8
12. ? @ 0x00000000000e5edc
; 142)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 528, in receive_hello
    raise self.receive_exception()
clickhouse_driver.errors.ServerException: Code: 516.
DB::Exception: clickhouse_admin: Authentication failed: password is incorrect, or there is no user with such name.. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, String const&) const @ 0x000000000ed2a3e0
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x000000000fe3cc28
4. DB::TCPHandler::receiveHello() @ 0x000000001100f318
5. DB::TCPHandler::runImpl() @ 0x0000000011006638
6. DB::TCPHandler::run() @ 0x000000001101d7e4
7. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
9. Poco::PooledThread::run() @ 0x000000001385d0b8
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
11. ? @ 0x000000000007d5c8
12. ? @ 0x00000000000e5edc

[2024-11-30T16:40:56.920+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-30T16:40:56.931+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T16:40:56.933+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
